name: interactivems
description: IMS StreamPulse — 4-up live HLS multiview for Android TV / Mi Box.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
